### ISSUE TITLE
Code for adding gpg key to keyrings dir

### ISSUE THREAD

**Issue by jlotto8** [MonetCarriere/Project-AWS#42]
# Download and add the HashiCorp GPG key to /etc/apt/keyrings
  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/hashicorp.gpg

**Comment by jlotto8** [comment]
@DevinBeu make this better lol

The Hashicorp repo provides the Terraform package, so it may not have been added correctly. We need to make sure it's added properly before attempting to install TF.

I think we should include explicit steps to add the repo, and update the package list. 
We also need specific feedback messages to track each step clearly.

**Comment by stephenlauck** [comment]
@jlotto8 yes, this is the way.
