### ISSUE TITLE
Update the README for multipass exec...

### ISSUE THREAD

**Issue by MonetCarriere** [MonetCarriere/Project-AWS#66]
Stephen made the suggestion that for #3 in the README, instead of having:
**multipass shell awesome-vm
bash terraformInstall.sh**

He instead wants us to use:
**multipass exec**

For context: The multipass exec command allows you to execute a command inside a running virtual machine (VM) managed by Multipass.

**Comment by jlotto8** [comment]
Mo completed, branch merged.
